NewDjangoProj/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, reverse_lazy
from test_django import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('info/', views.show_info, name='info'),
    path('info/<int:id_user>/edit', views.edit_mechanic, name='edit_mechanic'),
    path('info/messages/', views.show_messages, name='show_messages'),
    path('info/messages/<int:message_id>/accept', views.accept_car, name='accept_car'),
    path('', views.show_index, name='signup'),
    path('showclient/<int:id_user>/', views.show_client),
    path('showclient/<int:id_user>/edit/', views.edit_client, name='edit_client'),
    path('showclient/<int:id_user>/addcar/', views.create_car, name='create_car'),
    path('info/carinfo/<int:car_id>/', views.car_info, name='car_info'),
    path('info/carinfo/<int:car_id>/status/', views.change_car_status, name='change_car_status'),
    path('info/carinfo/<int:car_id>/delete/', views.delete_car, name='delete_car'),
    path('signin/', views.show_sign_in, name='signin'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('signup')), name='logout'),
    path('ajax/validate_username_email', views.validate_username_email, name='validate_username_email'),
    path('ajax/validate_mileage', views.validate_mileage, name='validate_mileage'),
]

test_django/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.contrib.auth.models import User
from django.forms.widgets import HiddenInput
from django import forms


class IntegerRangeField(models.IntegerField):
    def __init__(self, verbose_name=None, name=None, min_value=None, max_value=None, **kwargs):
        self.min_value, self.max_value = min_value, max_value
        models.IntegerField.__init__(self, verbose_name, name, **kwargs)

    def formfield(self, **kwargs):
        defaults = {'min_value': self.min_value, 'max_value': self.max_value}
        defaults.update(**kwargs)
        return super(IntegerRangeField, self).formfield(**defaults)

''''''
class Department(models.Model):
    address = models.TextField(verbose_name="Address", help_text="Enter an address",
                               null=False, blank=False)
    workload = IntegerRangeField(max_value=10, min_value=0, verbose_name="Workload(0 - none, 10 - full)",
                                 help_text="Choose an workload", null=False, blank=False)
    rating = IntegerRangeField(max_value=10, min_value=0, verbose_name="Rating(0 - puke, 10 - super)",
                               help_text="Choose a rating", null=False, blank=False)

    def __str__(self):
        return "Department address: " + self.address

    class Meta:
        db_table = "Department"


class Mechanic(models.Model):
    first_name = models.CharField(max_length=50, verbose_name="First Name", help_text="Enter a first name",
                                  null=False, blank=False)
    surname = models.CharField(max_length=50, verbose_name="Surname", help_text="Enter a surname",
                               null=False, blank=False)
    experience = IntegerRangeField(max_value=100, min_value=0, verbose_name="Experience",
                                   help_text="Choose an experience", null=False, blank=False)
    rating = IntegerRangeField(max_value=10, min_value=0, verbose_name="Rating(0 - puke, 10 - super)",
                               help_text="Choose a rating", null=False, blank=False)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, verbose_name="Department",
                                   help_text="Choose a department", null=False, blank=False)
    id_user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Id User", help_text="Choose an id user",
                                null=True, blank=True)

    def __str__(self):
        return "Mechanic: " + self.surname + " " + self.first_name + ". Rating: " + str(self.rating) + ". " \
               + self.department.__str__()

    class Meta:
        db_table = "Mechanic"


class Client(models.Model):
    first_name = models.CharField(max_length=50, verbose_name="First Name", help_text="Enter a first name",
                                  null=False, blank=False)
    surname = models.CharField(max_length=50, verbose_name="Surname", help_text="Enter a surname",
                               null=False, blank=False)
    phone_number = models.CharField(max_length=20, verbose_name="Phone Number", help_text="Enter a phone number",
                                    null=False, blank=False)
    city = models.CharField(max_length=50, verbose_name="City", help_text="Enter a city",
                            null=False, blank=False, default="Moscow")
    id_user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Id User", help_text="Choose an id user",
                                null=True, blank=True)

    def __str__(self):
        return "Client: " + self.surname + " " + self.first_name

    class Meta:
        db_table = "Client"


class Message(models.Model):
    title = models.CharField(max_length=50, verbose_name="Message title", help_text="Enter a message title",
                                  null=False, blank=False)
    body = models.CharField(max_length=150, verbose_name="Message body", help_text="Enter a message body",
                                  null=False, blank=False)
    isAccepted = models.BooleanField(default=False, null=False, blank=False)
    main_mech = models.ForeignKey(Mechanic, on_delete=models.CASCADE, null=True, blank=False)

    def __str__(self):
        return "Message: " + self.title

    class Meta:
        db_table = "Message"



class Car(models.Model):
    name = models.CharField(max_length=50, verbose_name="Name", help_text="Enter a name",
                            null=False, blank=False)
    mileage = models.IntegerField(verbose_name="Mileage", help_text="Enter a mileage",
                                  null=False, blank=False)
    malfunction = models.TextField(verbose_name="Malfunction", help_text="Enter a malfunction",
                                   null=False, blank=False)
    mechanics = models.ManyToManyField(Mechanic, verbose_name="Mechanic(s)",
                                        help_text="Choose a mechanic(s)", null=True, blank=False)
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name="Message",
                                        help_text="Choose a message", null=True, blank=False)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name="Client",
                               help_text="Choose a client", null=False, blank=False)
    repairIsDone = models.BooleanField(default=False, null=False, blank=False)

    def __str__(self):
        return "Car: " + self.name

    class Meta:
        db_table = "Car"


#something like supertool
# Create your models here.

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/infoStyle.css' %}">
    <style>
        header{
            position: fixed;
            width: 100%;
            margin-bottom: 45%;
        }
    </style>
</head>
<header>
<!-- partial:index.partial.html -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<nav class="navbar navbar-inverse" style="position: static">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">

                    <div class="navbar-header">
                        <button class="navbar-toggle" data-target="#mobile_menu" data-toggle="collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a href="#" class="navbar-brand">HELP.ME</a>
                    </div>

                    <div class="navbar-collapse collapse" id="mobile_menu">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="{% url 'info' %}">Home</a></li>
                            <li><a href="#" class="dropdown-toggle" data-toggle="dropdown">About Me<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">I wanna sleep</a></li>
                                    <li><a href="#">20 YO</a></li>
                                    <li><a href="#">Developed By</a></li>
                                    <li><a href="#">Ivanov Georgiy</a></li>
                                </ul>
                            </li>
                            <li><a href="#">Welcome To My Project <3</a></li>
                        </ul>


                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="#"><span class="glyphicon glyphicon-user"></span> Profile</a></li>
                            <li>
                                <a href="{% url 'logout' %}">
                                    Logout
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </nav>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</header>
<body style="background-color: #494d5f;" >
{% block content %}
{% endblock %}
</body>
</html>

templates/carInfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Car Info</title>
    {% extends "base.html" %}
</head>
<body>
{% block content %}
    <form class="form-horizontal" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label class="col-sm-2 control-label" style="margin-right: 10px">Name</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" readonly placeholder="{{ car.name }}">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" style="margin-right: 10px">Malfunction</label>
            <div class="col-sm-10">
                <input type="" class="form-control" readonly placeholder="{{ car.malfunction }}">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" style="margin-right: 10px">Mileage</label>
            <div class="col-sm-10">
                <input type="" class="form-control" readonly placeholder="{{ car.mileage }}">
            </div>
        </div>
        <div class="form-group">
            {% if car.mechanics.all.count == 1 %}
                <label class="col-sm-2 control-label" style="margin-right: 10px">Mechanic</label>
            {% elif car.mechanics.all.count > 1 %}
                <label class="col-sm-2 control-label" style="margin-right: 10px">Mechanics</label>
            {% else %}
                <label class="col-sm-2 control-label" style="margin-right: 10px"></label>
            {% endif %}
            <div class="col-sm-10">
                {% for mech in car.mechanics.all %}
                    {% if car.message.main_mech.id == mech.id %}
                        <input type="" class="form-control" readonly placeholder="Main: {{ mech.first_name }} {{ mech.surname }}">
                    {% else %}
                        <input type="" class="form-control" readonly placeholder="{{ mech.first_name }} {{ mech.surname }}">
                    {% endif %}
                {% endfor %}
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" style="margin-right: 10px">Client</label>
            <div class="col-sm-10">
                <input type="" class="form-control" readonly
                       placeholder="{{ car.client.first_name }} {{ car.client.surname }}">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" style="margin-right: 10px">Repair</label>
            <div class="col-sm-10">
                <input type="" class="form-control" readonly placeholder="{{ car.repairIsDone }}">
            </div>
        </div>
        <div class="form-group" style="margin-left: -60px; margin-top: 30px">
            <div class="col-sm-offset-2 col-sm-10">
                <a class="btn bg-warning" href='{% url 'info' %}'>Back</a>
                <a class="btn bg-success" href='{% url 'change_car_status' car.id %}'>Repair ✓/✗</a>
                <a class="btn bg-danger" href='{% url 'delete_car' car.id %}'>Delete</a>
            </div>
        </div>
    </form>
{% endblock %}
</body>
</html>

templates/clientInfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Client Information</title>
    {% extends "base.html" %}

</head>
<body>
{% block content %}
    <!-- partial:index.partial.html -->
    <div style="height: 50px;"></div>
    <div class="card-container">

        <img class="round" src="https://randomuser.me/api/portraits/{{ sex }}/{{ number }}.jpg"
             alt="user" style="cursor: pointer;"/>
        <h3>{{ client.first_name }} {{ client.surname }}</h3>
        <h6>City: {{ client.city }}</h6>
        <p> Phone: {{ client.phone_number }}</p>
        <div class="buttons">
            <button class="primary"
                    onclick="location.href='{% url 'edit_client' client.id_user_id %}'">
                Edit
            </button>
            <button class="primary ghost"
                    onclick="location.href='{% url 'create_car' client.id_user_id %}'">
                Add Car
            </button>
        </div>
        <div class="table-wrapper">
            {% if cars|length > 0 %}
                <h6>Cars</h6>
                <table class="fl-table" width="320px">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Car Info</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for car in cars %}
                        {% if car.repairIsDone == False %}
                            <tr>
                                <th>{{ car.name }}</th>
                                {% if car.message.isAccepted == True %}
                                    <th>Repaired: {{ car.repairIsDone }}</th>
                                {% else %}
                                    <th>Accepted: False</th>
                                {% endif %}
                            </tr>
                        {% endif %}
                    {% endfor %}
                    <tbody>
                </table>
            {% elif cars|length == 0 %}
                <h6>You have no cars.</h6>
            {% endif %}
        </div>
    </div>

{% endblock %}
</body>
</html>

templates/createCarForm.html
{% load crispy_forms_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register a Car</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    {% load crispy_forms_tags %}
</head>
<body style="background: #494d5f">

    {% block content %}
        <div class="container" style="">
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <div class="card" style="color:#B3B8CD; background: #231E39">
                        <div class="card-body">
                            <h5 class="card-title">
                                <a>Register a car</a>
                            </h5>
                            <div class="card-text">
                            <form action="" method="POST" novalidate id="contactForm">
                                {% csrf_token %}
                                {{ form|crispy }}
                                {{ message_form|crispy }}
                                <button type="submit"
                                        class="btn btn-secondary"
                                        id="add_button"
                                        style="width: 80px">
                                    Submit
                                </button>
                            </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    {% block javascript %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

    <script>
        $(document).ready(function (){
            $('#id_mileage').keyup(function (){
                $.ajax(
                {
                    data: $(this).serialize(),
                    url: "{% url 'validate_mileage' %}",
                    success:
                        function (response){
                        if($('#mileageError').length == 0)
                            $('#id_mileage').after('<div class="invalid-feedback d-block" id="mileageError" style="font-size: 13px"></div>');
                        if(response.mileage_pos == false){
                            $('#mileageError').removeClass('valid-feedback').addClass('invalid-feedback').text("Mileage cannot be negative");
                            $('#add_button').prop('disabled', true)
                        } else {
                            $('#mileageError').removeClass('invalid-feedback').addClass('valid-feedback').text("");
                            $('#add_button').prop('disabled', false)
                        }
                        },
                    error: function (response){
                        console.log(response.responseJSON.errors);
                    }
                }
            );
                return false;
            });
        });
    </script>
    {% endblock javascript %}
</body>
</html>

templates/formTemplate.html
{% load crispy_forms_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Profile</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
          integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    {% load crispy_forms_tags %}
</head>
<body style="background: #494d5f">

{% block content %}
    <div class="container" style="">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div class="card" style="color:#B3B8CD; background: #231E39">
                    <div class="card-body">
                        <h5 class="card-title">
                            <a>Edit Profile</a>
                        </h5>
                        <div class="card-text">
                            <form action="" method="POST" novalidate id="contactForm">
                                {% csrf_token %}

                                {{ form.first_name|as_crispy_field }}
                                {% if client.first_name != "" %}
                                    <div style="font-size: 13px">Old first name: {{ client.first_name }}</div><br>
                                {% endif %}

                                {{ form.surname|as_crispy_field }}
                                {% if client.surname != "" %}
                                    <div style="font-size: 13px">Old surname: {{ client.surname }}</div><br>
                                {% endif %}

                                {{ form.city|as_crispy_field }}
                                {% if client.city != "" %}
                                    <div style="font-size: 13px">Old city: {{ client.city }}</div><br>
                                {% endif %}

                                {{ form.phone_number|as_crispy_field }}
                                {% if client.phone_number != "" %}
                                    <div style="font-size: 13px">Old phone number: {{ client.phone_number }}</div><br>
                                {% endif %}

                                <button type="submit"
                                        class="btn btn-secondary"
                                        id="add_button"
                                        style="width: 80px">
                                    Submit
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
        crossorigin="anonymous"></script>

{% block javascript %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

    <script src="/static/javascript/jquery.maskedinput.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#id_phone_number").mask("+7 (999) 999-9999");
        });
    </script>
{% endblock javascript %}
</body>
</html>

templates/mechanicForm.html
{% load crispy_forms_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Profile</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
          integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    {% load crispy_forms_tags %}
</head>
<body style="background: #494d5f">

{% block content %}
    <div class="container" style="">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div class="card" style="color:#B3B8CD; background: #231E39">
                    <div class="card-body">
                        <h5 class="card-title">
                            <a>Edit Profile</a>
                        </h5>
                        <div class="card-text">
                            <form action="" method="POST" novalidate id="contactForm">
                                {% csrf_token %}

                                {{ form.first_name|as_crispy_field }}
                                {% if mech.first_name != "" %}
                                    <div style="font-size: 13px">Old first name: {{ mech.first_name }}</div><br>
                                {% endif %}

                                {{ form.surname|as_crispy_field }}
                                {% if mech.surname != "" %}
                                    <div style="font-size: 13px">Old surname: {{ mech.surname }}</div><br>
                                {% endif %}

                                {{ form.department|as_crispy_field }}
                                <div style="font-size: 13px">Old department address: {{ mech.department.address }}</div><br>


                                {{ form.experience|as_crispy_field }}
                                {% if mech.experience != "" %}
                                    <div style="font-size: 13px">Old experience: {{ mech.experience }}</div><br>
                                {% endif %}

                                {{ form.rating|as_crispy_field }}
                                {% if mech.rating != "" %}
                                    <div style="font-size: 13px">Old rating: {{ mech.rating }}</div><br>
                                {% endif %}

                                <button type="submit"
                                        class="btn btn-secondary"
                                        id="add_button"
                                        style="width: 80px">
                                    Submit
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
        crossorigin="anonymous"></script>
</body>
</html>

templates/mechanicInfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mechanic Information</title>
    {% extends "base.html" %}
</head>
<body>
{% block content %}
    <div style="height: 50px;"></div>
    <div class="card-container">
        <span class="pro" style="">PRO</span>
        <img class="round" src="https://randomuser.me/api/portraits/{{ sex }}/{{ number }}.jpg" alt="user"/>
        <h3>{{ mechanic.first_name }} {{ mechanic.surname }}</h3>
        <p>{{ mechanic.department }}</p>
        <p>Experience: {{ mechanic.experience }}</p>
        <p>Rating: {{ mechanic.rating }}</p>
        <div class="buttons">
            <button class="primary"
                    onclick="location.href='{% url 'edit_mechanic' mechanic.id_user_id %}'">
                Edit
            </button>
            <button class="primary ghost"
                    onclick="location.href='{% url 'show_messages' %}'">
                Messages
            </button>
        </div>
        <div class="table-wrapper">
            {% if cars|length > 0 %}
                <h6>Cars</h6>
                <table class="fl-table" style="width: 320px">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Mileage</th>
                        <th>Repair ✔</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for car in cars %}
                        {% if car.message.isAccepted == True %}
                            <tr>
                                <th><a href="{% url 'car_info' car_id=car.id %}">{{ car.name }}</a></th>
                                <th>{{ car.mileage }}</th>
                                <th>{{ car.repairIsDone }}</th>
                            </tr>
                            {% else %}
                            <tr>
                            <th>You have a message!</th>
                            </tr>
                        {% endif %}
                    {% endfor %}
                    <tbody>
                </table>
            {% elif cars|length == 0 %}
                <h6>You have no cars for repair.</h6>
            {% endif %}
        </div>
    </div>
{% endblock %}
</body>
</html>

templates/messagesInfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% extends "base.html" %}
</head>
<body>
{% block content %}
    <div class="container">
        {% if cars|length > 0 %}
            <h2>Messages</h2>
            <table class="table">
                <thead>
                <tr>
                    <th>Message Title</th>
                    <th>Message Body</th>
                    <th>Car Name</th>
                    <th>Car Malfunction</th>
                    <th>Accept Work</th>
                    <th>Refuse Work</th>
                </tr>
                </thead>
                <tbody>
                <tbody>
                {% for car in cars %}
                    {% if car.message.isAccepted == False %}
                        <th>{{ car.message.title }}</th>
                        <th>{{ car.message.body }}</th>
                        <th>{{ car.name }}</th>
                        <th>{{ car.malfunction }}</th>
                        <th><a class="btn bg-warning" href="{% url 'accept_car' car.message.id %}">Accept</a></th>
                        <th><a class="btn bg-warning" href="{% url 'delete_car' car.id %}">Refuse</a></th>
                    {% endif %}
                {% endfor %}
                <tbody>
            </table>
        {% elif messages|length == 0 %}
            <h6>You have no messages.</h6>
        {% endif %}
    </div>
{% endblock %}
</body>
</html>

templates/noAccess.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error!</title>
</head>
<body>
    <h1>You are not registered or do not have special rights!</h1>
</body>
</html>

templates/signIn.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Sign In</title>
  <meta name="viewport" content="width=device-width">
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/signStyle.css' %}">

</head>
<body>
    <div class='bold-line'></div>
    <div class='container'>
        <div class='window'>
            <div class='overlay'></div>
            <div class='content'>
                <div class='welcome'>Welcome back!</div>

                <div class='subtitle'>
                    <img src="https://cdn-icons-png.flaticon.com/512/675/675579.png" alt="img" height=60px>
                </div>


                <form method="post">
                    {% csrf_token %}
                    <div class='input-fields'>
                        <input type='email' name="email" placeholder='Email' class='input-line full-width'/>
                        <input type='password' name="password" placeholder='Password' class='input-line full-width'/>
                    </div>

                    <div class='spacing'>Do not have an account?
                        <span class='highlight' onclick="location.href='{% url 'signup' %}'">
                                Sign Up
                        </span>
                    </div>
                    <div>
                        <button class='ghost-round full-width'>
                            Sign In
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
<!-- partial -->

</body>
</html>